<?php
/**
 * Implements hook_user_login().
 */
function login_watch_user_login(&$edit, $account) {
  db_insert('login_tracker')
  ->fields(array('uid' => $account->uid, 'timestamp' => REQUEST_TIME))
  ->execute();
}
/**
 * Implements hook_permission().
 */
function login_watch_permission() {
  return array(
    'access module page' => array(
      'title' => t('Give access to view stats page'),
    ),
  );
}
/**
 * Implements hook_menu().
 */
function login_watch_menu() {
$items = array();
  $items['admin/config/people/login_watch'] = array(
    'title' => 'Login Watch module',
    'description' => 'Show login information of registered users.',
    'page callback' => 'login_watch_create_timestamp_table',
    'access arguments' => array('access module page'),
  );
  $items['admin/config/people/login_watch/timestamps'] = array(
    'title' => 'Last login timestamps',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
);
  $items['admin/config/people/login_watch/counter'] = array(
    'title' => 'Login Сounter',
    'access arguments' => array('access module page'),
    'page callback' => 'login_watch_create_counter_table',
    'file' => 'login_watch_counter.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  return $items;
}
/**
 * Create and render a table.
 */
function login_watch_create_timestamp_table() {
  $perpage = 10;
  $rows = array();
  $header = array(
    array(
      'data' => t('Login date'),
      'field' => 'timestamp' ,
      'sort' => 'desc'
    ),
    array(
      'data' => t('uid'),
      'field' => 'uid',
    ),
    array(
      'data' => t('User'),
      'field' => 'name'
    )
  );
  $result = timestamp_query($header, $perpage);
  $rows = fill_timestamp_table($result);
  $table_timestamp = theme('table', array('header' => $header, 'rows' => $rows));
  $table_timestamp .= theme('pager');
  return $table;
}
/**
 * Create a query from DB to fill the table.
 */
function timestamp_query($header, $perpage) {
  $select = db_select('users', 'u')->extend('TableSort')->extend('PagerDefault');
  $select->innerJoin('login_tracker', 'l', 'l.uid = u.uid');
  $select->fields('u', array('uid', 'name'))->fields('l', array('uid', 'timestamp'))->orderByHeader($header)->limit($perpage);
  $result = $select->execute();
  return $result;
}
/**
 * Fill the table.
 */
function fill_timestamp_table($result) {
  $timezone = variable_get('date_default_timezone');
  $rows = array();
  while ($value = $result->fetchAssoc()) {
    $rows[] = array(
      format_date($value['timestamp'], 'short', '', $timezone),
      $value['uid'],
      $value['name'],
    );
  }
  return $rows;
}
