<?php
/**
 * Implements hook_user_login().
 */
function login_watch_user_login(&$edit, $account) {
  db_insert('login_tracker')
  ->fields(array('uid' => $account->uid))
  ->execute();
}
/**
 * Implements hook_permission().
 */
function login_watch_permission() {
  return array(
    'access module page' => array(
      'title' => t('Give access to view stats page'),
    ),
  );
}
/**
 * Implements hook_menu().
 */
function login_watch_menu() {
$items = array();
  $items['admin/config/people/login_watch'] = array(
    'title' => 'Login Watch module',
    'description' => 'Show login information of registered users.',
    'page callback' => 'login_watch_timestamp_table',
    'access arguments' => array('access module page'),
  );
  $items['admin/config/people/login_watch/timestamps'] = array(
    'title' => 'Last login timestamps',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
);
  $items['admin/config/people/login_watch/counter'] = array(
    'title' => 'Login Counter',
    'access arguments' => array('access module page'),
    'page callback' => 'login_watch_counter_table',
    'file' => 'login_watch_counter.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  return $items;
}
/**
 * Create a query from DB to fill the table.
 */
function login_watch_create_timestamp_query() {
  $select = db_select('users', 'u')
    ->extend('TableSort')
    ->extend('PagerDefault')
    ->fields('u', array('uid', 'name'))
    ->fields('l', array('uid', 'timestamp'))
    ->orderByHeader($header)
    ->limit(10);
  $select->innerJoin('login_tracker', 'l', 'l.uid = u.uid');
  $result = $select->execute()->fetchAllAssoc();
  return $result;
}
/**
 * Implements theme_table.
 */
function login_watch_timestamp_table() {
  $perpage = 10;
  $result = login_watch_create_timestamp_query();
  $timezone = variable_get('date_default_timezone');
  $header = array(
    array(
      'data' => t('Login date'),
      'field' => 'timestamp' ,
    ),
    array(
      'data' => t('uid'),
      'field' => 'uid',
    ),
    array(
      'data' => t('User'),
      'field' => 'name'
    )
  );
  $rows = array();
  while ($value = $result) {
    $rows[] = array(
      format_date($value['timestamp'], 'short', '', $timezone),
      $value['uid'],
      $value['name'],
    );
  }
  $output = theme('table', array('header' => $header, 'rows' => $rows));
  $output .= theme('pager');
  return $output;
}
